### ISSUE TITLE
Hardcoded img path in sass files

### ISSUE THREAD

**Issue by acrobat** [Kunstmaan/KunstmaanCookieBundle#21]
I've tried using the cookie bundle in a setup without the "regular" kunstmaan frontend setup instead webpack (encore) was used for the frontend build. But webpack tries to resolve the paths/urls found in sass files by default. 

So the import and build of this file fails because the same path does not exists in my project. See https://github.com/Kunstmaan/KunstmaanCookieBundle/blob/master/src/Resources/ui/scss/components/_btn-toggle.scss#L39 and https://github.com/Kunstmaan/KunstmaanCookieBundle/blob/master/src/Resources/ui/scss/components/_btn-toggle.scss#L78

A possible solution could be to introduce a variable with the basepath which the user can override before importing the sass files.

**Comment by diskwriter** [comment]
Ah yes, good point. 

@sector32 Could you take a look at this, please?

**Comment by acrobat** [comment]
@diskwriter same for some twig files, example: https://github.com/Kunstmaan/KunstmaanCookieBundle/blob/master/src/Resources/views/Components/CookieBar.html.twig#L11

But I don't know a good solution (yet) for this

**Comment by diskwriter** [comment]
@acrobat Could we extract that bit to an extra file, that you could override from app/ ?

**Comment by sector32** [comment]
Regarding the usage of svg images in the Twig files; is it an option to replace svg's by html tags which are styled by css? If so, I can store the svg files as variables in the same location as the btn-toggle ones.

**Comment by acrobat** [comment]
@diskwriter specific twig files for the svg could work, I currently override the full template file and replaced the paths with`asset('correct/path/to/image')`

@sector32 Don't know if that works for all browsers? @diskwriter @dbeerten could that also be a fix?

**Comment by sector32** [comment]
FYI: https://caniuse.com/#feat=svg-img

**Comment by sector32** [comment]
FYI: Using the img tag is not an option. I will move both svg usages to seperate twig files.
